Bump shell integration

diff --git a/OtherResources/Utilities/it2copy b/OtherResources/Utilities/it2copy
--- a/OtherResources/Utilities/it2copy
+++ b/OtherResources/Utilities/it2copy
@@ -79,6 +79,10 @@ send() {
     fi
 }
 
+error() {
+    echo "ERROR: $*" 1>&2
+}
+
 # Look for command line flags.
 while [ $# -gt 0 ]; do
     case "$1" in
